# Generated by Django 3.0.5 on 2020-09-27 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('ownaddress', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('licenses', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('agencyaddress', models.CharField(max_length=50)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
