# Generated by Django 3.0.5 on 2020-09-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
