# Generated by Django 3.0.5 on 2020-09-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200929_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
