# Generated by Django 3.0.5 on 2020-09-29 09:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200929_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
